version: "3.9"
services:
# pgsql
  pgsql:
    image: mahakziroh2/zunu:docker_client_postgres_12
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      pgdb_user: ${pgdb_user}
      pgdb_password: ${pgdb_password}
    volumes:
    - "PGDATA:${PGDATA}"
    networks:
      - vault-network

# mongo
  mongo:
    image: "mongo:5.0.9"
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      - "MONGODATA:/data/db"
    networks:
      - vault-network

volumes:
  PGDATA:
  MONGODATA:
    external: false
networks:
  vault-network:
